services:

  server:
    container_name: server
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      MONGO_URL: mongodb://mongo
    restart: unless-stopped
    ports:
      - "8080:8080"
    links:
      - mongo
    depends_on:
      - mongo

  mongo:
    container_name: mongo
    image: mongo
    restart: unless-stopped
    ports:
      - "27017:27017"

  mongo-express:
    container_name: mongo-express
    image: mongo-express
    restart: unless-stopped
    depends_on:
      - mongo
    ports:
      - "8081:8081"
