name: Server

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  gradle:
    strategy:
      matrix:
        os: [ ubuntu-latest ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v1

      - uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Cache Build files
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle
          key: ${{ runner.os }}-${{ hashFiles('gradle.properties') }}

      - name: Start MongoDB
        uses: supercharge/mongodb-github-action@1.3.0
        with:
          mongodb-version: 4.4

      - uses: eskatos/gradle-command-action@v1
        with:
          arguments: |
            :caroline-server:caroline-server-bundled:check
            :caroline-server:caroline-server-core:check
            :caroline-server:caroline-server-bundled:installShadowDist
